name: builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 21 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: apt
      run: |-
        sudo apt update
        sudo apt install -y build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools rsync subversion swig time xsltproc zlib1g-dev
    - name: download
      run: wget https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64.tar.xz
    - name: extract
      run: tar xvJf openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64.tar.xz
    - name: build
      run: |-
        cd openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64
        make image PROFILE="tplink_tl-mr6400-v4" PACKAGES="modemmanager"
    - name: release
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64/bin/targets/ramips/mt76x8/*.bin"]'

