name: builder

on:
  push:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: apt
      run: |-
        sudo apt update
        sudo apt install -y build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools rsync subversion swig time xsltproc zlib1g-dev
    - name: download
      run: wget https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64.tar.xz
    - name: extract
      run: tar xvJf openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64.tar.xz
    - name: build
      run: |-
        cd openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64
        make image PROFILE="tplink_tl-mr6400-v4" PACKAGES="modemmanager luci-proto-modemmanager luci-proto-qmi luci-proto-3g luci-proto-ncm uhttpd uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-mod-admin-full luci-theme-bootstrap -ppp -ppp-mod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only luci-app-sms-tool"
    - name: generate-tag-name
      run: echo "TAG_NAME=refs/tags/v$(date '+%Y%m%d_3')" >> $GITHUB_ENV
    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        body: "OpenWrt for TP-Link TL-MR6400 V4 with ModemManager included. "
        file: openwrt-imagebuilder-ramips-mt76x8.Linux-x86_64/bin/targets/ramips/mt76x8/*.bin
        file_glob: true
        tag: ${{ env.TAG_NAME }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
